### PR TITLE
Fix output path of Terra wdio Spec Reporter's results when one spec is ran

### LINKED ISSUE #42: Incorrect WDIO reporter tool output location
# Bug Report

## Description

After pulling in the most recent version of terra-toolkit (6.4.0), we are seeing the WDIO reporter tool that was added in placing the report JSON in the incorrect location. Instead of nesting the report in the generated 'reports' folder, it generates it within the 'wdio' folder. This causes the generated report to by-pass gitignore setting for reports folders.

## Steps to Reproduce

1. Have a WDIO spec set up, with the project using terra-toolkit 6.4.0
2. Run 'npm run test:wdio'
3. See output report location

## Additional Context / Screenshots

Here is a screenshot of the file-structure output for reference (project name blocked out):
terra-toolkit-issue

## Expected Behavior

The outputted report file should have been nested within the generated reports folder as far as I am aware from reading the change docs and code change itself.

## Possible Solution

I assume it has to do with the pathing/generation of the report in the update to the wdio configuration file that was made in one of the recent 6.x.0 releases.

## Environment

* Component Name and Version: terra-toolkit, 6.4.0
* Browser Name and Version: N/A
* Node/npm Version: [e.g. Node 8/npm 5] Node 10.16.0 / npm 6.9.0
* Webpack Version: 4.43.0 (^4.30.0 in package.json)
* Operating System and version (desktop or mobile): Desktop, Ubuntu 18.04.4 run through a virtualbox VM

## @ Mentions

I was told to log this issue by @emilyrohrbough

### PR DESCRIPTION
**Pull request by emilyrohrbough**
### Summary

* Fix Terra wdio Spec Reporter output location when only one spec file is ran.
* Fix default out path for reports to match the default reports path included in default wdio configuration
* Add additional jest tests

Resolves #42 

### Additional Details

@cerner/terra

[CONTRIBUTORS.md]: ../blob/main/CONTRIBUTORS.md
[License]: ../blob/main/LICENSE

### CODE REVIEW

File: reporters/wdio/TerraWDIOSpecReporter.js [hunk 1]
```diff
@@ -65,20 +52,26 @@ class TerraWDIOSpecReporter extends WDIOSpecReporter {
   * @param {object} [options.reporterOptions.outputDir] - output dir path for results dir
   * @return string
```
Comment (StephenEsser) [inline reporters/wdio/TerraWDIOSpecReporter.js:53]: The param and return documentation need to be updated/removed.

File: reporters/wdio/TerraWDIOSpecReporter.js [hunk 2]
```diff
@@ -65,20 +52,26 @@ class TerraWDIOSpecReporter extends WDIOSpecReporter {
...
   */
-  setResultsDir(options) {
-    if (options.reporterOptions && options.reporterOptions.outputDir) {
-      return options.reporterOptions.outputDir;
+  setResultsDir() {
+    const { reporterOptions } = this.options;
+    if (reporterOptions && reporterOptions.outputDir) {
+      this.resultsDir = reporterOptions.outputDir;
```
Comment (StephenEsser) [inline reporters/wdio/TerraWDIOSpecReporter.js:58]: This is always reassigned below on line 65, what is this doing?
